# Generated by Django 5.0.3 on 2024-04-10 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news_sentiments', '0002_delete_article'),
        ('newsaggregator', '0007_rename_byline_health_h_byline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(max_length=10)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsaggregator.article')),
            ],
        ),
    ]
