# Generated by Django 5.0.3 on 2024-04-10 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_sentiments', '0003_initial'),
        ('newsaggregator', '0007_rename_byline_health_h_byline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthSentimentAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(max_length=10)),
                ('health_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsaggregator.article')),
            ],
        ),
        migrations.CreateModel(
            name='SportsSentimentAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(max_length=10)),
                ('sports_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsaggregator.article')),
            ],
        ),
    ]
