# Generated by Django 5.0.3 on 2024-03-26 14:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsaggregator', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Source',
        ),
        migrations.RemoveField(
            model_name='article',
            name='source',
        ),
        migrations.RemoveField(
            model_name='article',
            name='url',
        ),
        migrations.AddField(
            model_name='article',
            name='byline',
            field=models.TextField(
                default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='time',
            field=models.DateTimeField(default=None, null=True, blank=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
