# Generated by Django 5.0.3 on 2024-04-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsaggregator', '0005_article_sentiment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('byline', models.TextField(default='', max_length=255)),
                ('time', models.DateTimeField()),
                ('content', models.TextField()),
                ('sentiment', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('byline', models.TextField(default='', max_length=255)),
                ('time', models.DateTimeField()),
                ('content', models.TextField()),
                ('sentiment', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
