# Generated by Django 5.0.3 on 2024-04-10 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsaggregator', '0006_health_sports'),
    ]

    operations = [
        migrations.RenameField(
            model_name='health',
            old_name='byline',
            new_name='h_byline',
        ),
        migrations.RenameField(
            model_name='health',
            old_name='content',
            new_name='h_content',
        ),
        migrations.RenameField(
            model_name='health',
            old_name='sentiment',
            new_name='h_sentiment',
        ),
        migrations.RenameField(
            model_name='health',
            old_name='time',
            new_name='h_time',
        ),
        migrations.RenameField(
            model_name='health',
            old_name='title',
            new_name='h_title',
        ),
        migrations.RenameField(
            model_name='sports',
            old_name='byline',
            new_name='s_byline',
        ),
        migrations.RenameField(
            model_name='sports',
            old_name='content',
            new_name='s_content',
        ),
        migrations.RenameField(
            model_name='sports',
            old_name='sentiment',
            new_name='s_sentiment',
        ),
        migrations.RenameField(
            model_name='sports',
            old_name='time',
            new_name='s_time',
        ),
        migrations.RenameField(
            model_name='sports',
            old_name='title',
            new_name='s_title',
        ),
    ]
